services:
  backend:
    ports:
      - "8880:8000"
    volumes:
      - ./backend/laravel:/app
      - vendor_data:/app/vendor
    tty: true
    stdin_open: true

  frontend:
    ports:
      - "3055:80"

  db:
    ports:
      - "127.0.0.1:5433:5432"

volumes:
  vendor_data:
