services:
  backend:
    ports:
      - "127.0.0.1:8880:8000"
    volumes:
      - ./backend/laravel:/app
      - vendor_data:/app/vendor
    tty: true
    stdin_open: true

  reverb:
    ports:
      - "127.0.0.1:8081:8080"
    volumes:
      - ./backend/laravel:/app
      - vendor_data:/app/vendor

  queue:
    volumes:
      - ./backend/laravel:/app
      - vendor_data:/app/vendor

  frontend:
    ports:
      - "127.0.0.1:3055:80"

  db:
    ports:
      - "127.0.0.1:5433:5432"

volumes:
  vendor_data:
